function tbl = mayoFormat_trialDataTable(nev,dat,task_name)

    %DATAFOLDER = '/Users/kendranoneman/Data/SCRAPPY';
    %DATAFILE = 'scrappy_0056e_pursuit_leftFEF';

    %task_name = 'purs';
    
    % nevutils
    %[dat,~] = nev2dat(sprintf('%s/%s.nev',DATAFOLDER,DATAFILE),'readNS5',true,'convertEyes',true,'allowNevPause',true, 'include_0_255', true);
    
    %% Compile basic session details
    % Pull info from dat, generated by nevutils
    num_trials  =  length(dat);
    trialNames  =  cellfun(@(q) [task_name,char('.'),char(string(q))], num2cell(1:length(dat))','uni',0);
    
    % Pull out conditions from trial names, separated by ';' delimeter
    condNames = {dat.text}';
    pattern = '([^0-9;]+)(?==)';
    matches = cellfun(@(q) regexp(q, pattern, 'match'), condNames, 'uni', 0);
    cols = matches{1};
    conditions = cellfun(@(x) cellfun(@(q,r) str2double(x(q+1:r-1)), num2cell(strfind(x,'=')), num2cell(strfind(x,';')), 'uni', 0), {dat.text}.', 'uni', 0);
    conditions = vertcat(conditions{:}); 
    
    % Pull eye traces, spike times, and trial codes for each trial (cell for each trial)
    eye = {dat.eyedata}.'; % 3 x N (HE,VE,DI) x (N time points)
    %spks = cellfun(@(q,r,t) (cumsum([r; q]) - t)*1000, {dat.spiketimesdiff}.', {dat.firstspike}.', cellfun(@(q) q(1), {dat.time}.', 'uni', 0), 'uni', 0); 
    trialcodes = {dat.trialcodes}.'; % C x 3 (codes) x (chan,code,time)
    results = {dat.result}.';
    resultNames = convertBetween_eventCodes_eventNames(results);
    
    % Make array of times of start/end time per trial, for aligning with trial codes and indexing eye data
    times = cellfun(@(q) round(q(1)*1000:q(2)*1000), {dat.time}.', 'uni', 0);
    
    % 6. For trial code you want to align data to (could be trial start, target
    % onset, etc...), pull out eye traces around that point (preint, postint)
    trialStarts = cellfun(@(q,r) find(q == round(r(r(:,2)==1,3)*1000)), times, trialcodes, 'uni', 0);
    
    eventCodes = {dat.trialcodes}.'; eventCodes = vertcat(eventCodes{:});
    eventCodes = num2cell(sort(unique(eventCodes(:,2))))';
    %eventCodes = eventCodes(cell2mat(eventCodes)<2000);
    
    eventNames = convertBetween_eventCodes_eventNames(eventCodes);
    trialMarkers = cellfun(@(t) cellfun(@(q,r) find(q == round(r(r(:,2)==t,3)*1000)), times, trialcodes, 'uni', 0), eventCodes, 'uni', 0)';
    trialMarkers = horzcat(trialMarkers{:});
    trialMarkers(cellfun('isempty',trialMarkers)) = {NaN};
    
    %% Filter eye traces and calculate derivatives
    eyePos = cellfun(@(x,y) filterEyeTraces_EyeLink(x.trial(1:2,y:end),'SAMPLING_FREQUENCY',dat(1).eyedata.dataFs,'CUTOFF_FREQUENCY',84,'PLOT_TRIAL',false), eye, trialStarts, 'uni', 0);
    [thePos,radPos] = cellfun(@(q) cart2pol(q(1,:),q(2,:)), eyePos, 'uni', 0);
    
    eyeVel = cellfun(@(q) calcDerivative_eyeTraces(q), cellfun(@(x,y) filterEyeTraces_EyeLink(x.trial(1:2,y:end),'SAMPLING_FREQUENCY',dat(1).eyedata.dataFs,'CUTOFF_FREQUENCY',40,'PLOT_TRIAL',false), eye, trialStarts, 'uni', 0), 'uni', 0);
    eyeAcc = cellfun(@(q) calcDerivative_eyeTraces(q), eyeVel, 'uni', 0);

    [pursuitOnsets, rxnTimes, msFlags, csFlags] = deal(cell(num_trials, 1));
    for t = 1:num_trials
        targOnset = trialMarkers{t,ismember(string(eventNames),"TARG_ON")'};
        targSpeed = conditions{t,1};
        targDir = conditions{t,2};
        jumpType = conditions{t,3};
        if isequal(resultNames{t},'CORRECT')
            [~,radPos] = cart2pol(eyePos{t}(1,:),eyePos{t}(2,:));
            [pursuitOnset,rxnTime,msFlag,csFlag] = detect_pursuitOnset2(radPos,targOnset,dat(t).params.block.reactionTime,targSpeed,targDir,jumpType,0);
        else
            pursuitOnset = NaN;
            rxnTime = NaN; 
            msFlag = NaN;
            csFlag = NaN;
        end
        pursuitOnsets{t} = pursuitOnset;
        rxnTimes{t} = rxnTime;
        msFlags{t} = msFlag;
        csFlags{t} = csFlag;
    end

    % rewrite column names based on text in dat.text
    columnNames = ["trialName","trialOutcome","pursuitOnset","rxnTime","msFlag","csFlag",cols,string(eventNames)',"eyePos","eyeVel","eyeAcc"];
    tbl = cell2table([trialNames resultNames pursuitOnsets rxnTimes msFlags csFlags conditions trialMarkers cellfun(@(x){x},eyePos) cellfun(@(x){x},eyeVel) cellfun(@(x){x},eyeAcc)],'VariableNames',columnNames);
    tbl.trialName = categorical(string(tbl.trialName)); tbl.trialOutcome = categorical(string(tbl.trialOutcome));
    if ismember('emptyCnd', tbl.Properties.VariableNames)
        % Column exists, so remove it
        tbl = removevars(tbl, 'emptyCnd');
    end
    
    % 9. Save the table if you wish
    %save(sprintf('%s/processed/%s_processed.mat',DATAFOLDER,DATAFILE),'tbl','-v7');
end

